apiVersion: apps/v1
kind: Deployment
metadata:
  name: hurtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hurtop
  template:
    metadata:
      labels:
        app: hurtop
    spec:
      containers:
      - image: okteto.dev/hurtop:latest
        name: hurtop
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1c42cad9-eeaa-4caa-914d-972e20e8bb73"
        - name: Vless_Path
          value: "/vl58yt6555"
        - name: Vmess_UUID
          value: "1c42cad9-eeaa-4caa-914d-972e20e8bb73"
        - name: Vmess_Path
          value: "/vm6lkli66"
        - name: Share_Path
          value: "/v2link"
